# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql/

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
